# Generated by Django 4.2 on 2025-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Product barcode for scanning', max_length=50, null=True, unique=True),
        ),
    ]
